services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: client_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
