server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/account_db
    username: account
    password: account
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true