server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/client_db
    username: client
    password: client
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true