server:
  port: 8083

spring:
  application:
    name: record
  datasource:
    url: jdbc:postgresql://localhost:5433/record_db
    username: record
    password: record
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka