services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: client_db
      POSTGRES_USER: client
      POSTGRES_PASSWORD: client
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    restart: always
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
